name: Compilaci√≥n y pruebas C#
on: push
jobs:
  Compilacion:
    runs-on: windows-latest
    environment: PRUEBAS
    steps:
      - run: echo "El secreto Google es ${{ secrets.GOOGLE_TOKEN }}"  
      - uses: actions/checkout@v2
      - name: Compilamos
        run: dotnet build
      - name: Ejecutamos las pruebas
        run: dotnet test
